### PR TITLE
Cleanup whitespace formatting in markup

### PR DESCRIPTION
**Pull request by VincentH-Net**
### Description of Change
Cleanup whitespace formatting in markup of `UserInterface/CSharpMarkupDemos` to make it consistent with documentation examples for the C# Markup feature.

No code changes; built and tested on Android.
@davidbritch pls review

### CODE REVIEW

**Comment by davidbritch** [comment]
Afraid I can't merge it. I'll send you an email explaining why.

**Comment by VincentH-Net** [comment]
> Afraid I can't merge it. I'll send you an email explaining why.
Hi @davidbritch, did not receive your email yet - could you (re)send it to dev at vincenth.net? Thx!

**Comment by davidbritch** [comment]
@VincentH-Net 

Resent.

**Comment by davidbritch** [comment]
@VincentH-Net 

Reopened!

**Comment by VincentH-Net** [comment]
@davidbritch thanks for reopening; pls review.

I updated the whitespace formatting to comply with this Microsoft Visual Studio formatting rule for this repo:
> opening braces have to go on new lines

I did the same in `csharp-markup.md` and mailed it to you.

**Pull request merged**
