### PR TITLE
Fix weather app

### PR DESCRIPTION
**Pull request by gonzalonm**
Free API server may produce an overload while a request is executing. There is no solution to avoid this, but there is an approach to reduce the frequence of the problem. Here https://openweathermap.desk.com/customer/portal/questions/13084185-error-not-found-city suggest to use a simple request (zip and appid params).
If the API returns 404,  the app shouldn't crash. So, I've added a null-check to avoid crash in runtime.

### CODE REVIEW

**Comment by gonzalonm** [comment]
Bug: https://bugzilla.xamarin.com/show_bug.cgi?id=43918

**Comment by olegoid** [comment]
Nice, thanks @gonzalonm 👍

**Comment by olegoid** [comment]
@rzaitov should we merge this fix in any other branches(beside master)?

**Comment by gonzalonm** [comment]
@olegoid Parmendra suggests merge it into branch 2.3.3 "because forms 2.3.3-pre2 sample testing in progress"

**Comment by rzaitov** [comment]
@olegoid @gonzalonm It is safe (and desirable) to cherry pick it to 2.3.3 branch (because we didn't touch csproj, sln and packages files)

**Pull request merged**
