### PR TITLE
Update UI component

### PR DESCRIPTION
**Pull request by gonzalonm**
Using StackLayout instead of AbsoluteLayout

Bug: https://bugzilla.xamarin.com/show_bug.cgi?id=43466

### CODE REVIEW

**Comment by olegoid** [comment]
LGTM. However, it would be nice to have a second pair of eyes for this PR. @conceptdev could you take a look?

**Comment by conceptdev** [comment]
It's hard to compare what changes were made when the entire file is converted from tabs to spaces? If possible I'd always recommend sticking to the existing formatting style when making functional changes (and if formatting changes are required, do it a separate PR).

The code change itself looks good. 

If you have time, could you do me a favor and include screenshots for all the platforms? The sample didn't have them previously (which is a mistake on the part of the author) but if we have a chance to add them now, that would be GREAT.

**Comment by gonzalonm** [comment]
@conceptdev how does it look now? I was using a default code format in VS with spaces. I changed it in order to use tabs instead. Also, I've added screenshots for all the platforms.

**Comment by gonzalonm** [comment]
@conceptdev how does it look? I've added screenshots for all the platforms and I've used tabs instead of spaces. My apologies for that.

**Comment by conceptdev** [comment]
LTGM - thanks a lot! I really appreciate you taking the time to add the screenshots - makes it a better sample (fixing the bug does too!) ;)

**Comment by olegoid** [comment]
alright, it seems like all the parties are fine to merge now;)

**Pull request merged**
