### PR TITLE
Add Tizen project for samples

### PR DESCRIPTION
**Pull request by darkleem**
Tizen platform is supported publically on Xamarin Forms 3.0.0.482510 version.
(https://developer.tizen.org/blog/tizen-4.0-m2-released-visual-studio-tools-tizen)

### CODE REVIEW

**Comment by Piotr12** [comment]
### Description of Change
70 sample apps created for Tizen 

### Pull Request Checklist
- [x] Rebased on top of master at time of the pull request.
- [x] Changes adhere to coding standard in the sample.
- [x] Consolidated NuGet packages across all projects in the sample (when changing existing package versions). 
- [x] Tested changes on the appropriate platforms (all platforms if changing the library code).
  - all new apps tested on [tizen-4.0](http://download.tizen.org/snapshots/tizen/4.0-unified/tizen-4.0-unified_20180612.2/images/standard/mobile-wayland-armv7l-tm1/) mobile, (plus Wearable and TV where appropriate)

**Comment by sung-su** [comment]
@Piotr12 
Rebase and Add Tizen UserInterface/VsmDemos project

**Comment by Piotr12** [comment]
no problem @sung-su happy to see its corrected already!

**Comment by davidbritch** [comment]
Closed following a discussion with Samsung over email.

**Pull request closed without merging**
