### PR TITLE
Update TodoRest (ASP.NET Core 3.1 & Mobile Best Practices)

### PR DESCRIPTION
**Pull request by jamesmontemagno**
… Xamarin.Essentials for device detection.

### Pull Request Checklist

- [ ] Rebased on top of master at time of the pull request.
- [ ] Changes adhere to coding standard in the sample.
- [ ] Consolidated NuGet packages across all projects in the sample (when changing existing package versions).
- [ ] Tested changes on the appropriate platforms (all platforms if changing the library code).

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Ping @jongalloway @csharpfritz

**Comment by Rick-Anderson** [comment]
@davidbritch @jongalloway @csharpfritz can you review or recommend a reviewer. This needs to merge so we can import the code for our snippets in dotnet/AspNetCore.Docs#21434

**Comment by csharpfritz** [comment]
I’ll take a look when I get back to my office after dinner



Jeff

**Review by davidbritch — APPROVED** [review]

**Comment by davidbritch** [comment]
@Rick-Anderson Approved and merged.

**Pull request merged**
