### PR TITLE
fix for Issue #368

### PR DESCRIPTION
**Pull request by pmahend1**
### Description of Change

fix for Issue #368

### Pull Request Checklist

- [x] Rebased on top of master at time of the pull request.
- [x] Changes adhere to coding standard in the sample.
- [x] Consolidated NuGet packages across all projects in the sample (when changing existing package versions).
- [x] Tested changes on the appropriate platforms (all platforms if changing the library code).

### CODE REVIEW

**Comment by davidbritch** [comment]
Hi @pmahend1 

Thanks for this PR. I'll take a look at it this week (I'll also have to update the doc).

**Comment by davidbritch** [comment]
Hi @pmahend1 

Your PR looks good. However, until I can fully test it by setting up a new website to host the digital links asset file, and do a large update on the doc, I'm going to leave it here.

**Comment by pmahend1** [comment]
@davidbritch I am wondering what you mean by setting up new website. I dont think a new site has to be set up.URL patterns are deeplining/query . Thats not real website. Correct me if I am wrong.

**Comment by davidbritch** [comment]
Hi @pmahend1 

Apologies for the delay in dealing with this PR. I've made other changes to the sample, and so it was easier to incorporate your changes into my updated sample rather than merge the PR.

However, thanks for the fixes. Much appreciated.

**Pull request closed without merging**
